compras/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('compras/requisiciones_autorizadas', views.requisiciones_autorizadas, name='requisicion-autorizada'),
    path('compras/oc/<int:pk>/', views.oc_modal, name='oc'),
    path('update_oc/', views.update_oc, name='update-oc'),
    path('compras/matriz_compras/', views.matriz_oc, name='matriz-compras'),
    path('compras/upload_facturas/<int:pk>/', views.upload_facturas, name='upload-facturas'),
    path('compras/upload_xml/<int:pk>/', views.upload_xml, name='upload-xml'),
    path('compras/autorizacion_oc1/',views.autorizacion_oc1, name='autorizacion-oc1'),
    path('compras/autorizacion_oc2/',views.autorizacion_oc2, name='autorizacion-oc2'),
    path('compras/cancelar_oc1/<int:pk>/',views.cancelar_oc1, name='cancelar-oc1'),
    path('compras/regresar_oc/<int:pk>/',views.back_oc, name='back-oc'),
    path('compras/cancelar_oc2/<int:pk>/',views.cancelar_oc2, name='cancelar-oc2'),
    path('compras/autorizar_oc1/<int:pk>/', views.autorizar_oc1, name='autorizar-oc1'),
    path('compras/autorizar_oc2/<int:pk>/', views.autorizar_oc2, name='autorizar-oc2'),
    path('salida_material/oc_pdf/<int:pk>/', views.render_oc_pdf, name='oc-pdf'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
# De django.contrib.auth.models estamos importando el modelo de usuarios de la administration
from user.models import Distrito, Profile
from solicitudes.models import Proyecto, Subproyecto, Sector, Operacion, Activo
from djmoney.models.fields import MoneyField
from simple_history.models import HistoricalRecords
#from django.db.models.functions import TruncDate

# Create your models here.

class Familia(models.Model):
    nombre = models.CharField(max_length=20, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Unidad(models.Model):
    nombre = models.CharField(max_length=10, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Subfamilia(models.Model):
    nombre = models.CharField(max_length=15, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Product(models.Model):
    codigo = models.CharField(max_length=5, null=True, unique=True)
    nombre = models.CharField(max_length=100, null=True, unique=True)
    unidad = models.ForeignKey(Unidad, on_delete = models.CASCADE, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)
    subfamilia = models.ForeignKey(Subfamilia, on_delete =models.CASCADE, null=True)
    especialista = models.BooleanField(default=False)
    iva = models.BooleanField(default=True)
    activo = models.BooleanField(default=False)
    servicio = models.BooleanField(default=False)
    baja_item = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, upload_to='product_images')
    completado = models.BooleanField(default = False)

    #Estas opciones de guardado de creación y actualización las voy a utilizar en todos mis modelos
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.codigo}-{self.nombre}'


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Products_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash')
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)


    def __str__(self):
        return f'File id:{self.id}'



class Marca(models.Model):
    nombre = models.CharField(max_length=20, null=True, unique=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Inventario_Batch(models.Model):
    file_name = models.FileField(upload_to='inventario_batch')
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f'File id:{self.id}'

class Inventario(models.Model):
    producto = models.ForeignKey(Product, on_delete =models.CASCADE, null=True)
    distrito = models.ForeignKey(Distrito, on_delete = models.CASCADE, null=True)
    marca = models.ManyToManyField(Marca)
    cantidad = models.PositiveIntegerField(default=0)
    cantidad_apartada = models.PositiveIntegerField(default=0)
    cantidad_entradas = models.PositiveIntegerField(default=0)
    price = MoneyField(max_digits=14, decimal_places=2,default_currency= 'MXN',default=0)
    minimo = models.PositiveIntegerField(default =0)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    comentario = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        unique_together = ('producto', 'distrito',)

    def __str__(self):
        return f'{self.producto}'

class Tipo_Orden(models.Model):
    tipo = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f'{self.id}:{self.tipo}'

class Order(models.Model):
    folio = models.CharField(max_length=6, null=True, unique=True)
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Crea')
    proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)
    operacion = models.ForeignKey(Operacion, on_delete = models.CASCADE, null=True)
    #sector = models.ForeignKey(Sector, on_delete = models.CASCADE, null=True)
    superintendente = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='intendente')
    supervisor = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='supervisor')
    activo = models.ForeignKey(Activo, on_delete = models.CASCADE, null=True)
    requisitar = models.BooleanField(null=True, default=False)
    complete = models.BooleanField(null=True)
    tipo = models.ForeignKey(Tipo_Orden, on_delete=models.CASCADE, null=True)
    #sol_autorizada_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, blank=True, related_name='Autoriza')
    autorizar = models.BooleanField(null=True, default=None)
    created_at = models.DateField(null=True)
    created_at_time = models.TimeField(null=True)
    approved_at = models.DateField(null=True)
    approved_at_time = models.TimeField(null=True)

    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.id} -{self.folio} ordered by {self.staff}'


    @property
    def get_cart_total(self):
        productos = self.articulosordenados_set.all()
        total = sum([producto.get_total for producto in productos])
        return total

    @property
    def get_cart_quantity(self):
        productos = self.articulosordenados_set.all()
        total = sum([producto.cantidad for producto in productos])
        return total

    @property
    def get_folio(self):
        return str(self.pk).zfill(6)


class ArticulosOrdenados(models.Model):
    producto = models.ForeignKey(Inventario, on_delete = models.CASCADE, null=True)
    orden = models.ForeignKey(Order, on_delete = models.CASCADE, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.orden} - {self.producto}'

    @property
    def get_total(self):
        total = self.producto.price * self.cantidad
        return total

class ArticulosparaSurtir(models.Model):
    articulos = models.ForeignKey(ArticulosOrdenados, on_delete = models.CASCADE, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank= True)
    precio = MoneyField(max_digits=14, decimal_places=2, default_currency= 'MXN',default=0)
    surtir = models.BooleanField(default=False)
    cantidad_requisitar = models.IntegerField(default=0, null=True, blank=True)
    requisitar = models.BooleanField(null=True, default=False)
    salida = models.BooleanField(null=True, default=False)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    seleccionado = models.BooleanField(null=True, default=False)
    created_at = models.DateField(auto_now_add=True)
    created_at_time = models.TimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)


    def __str__(self):
        return f'{self.articulos} - {self.cantidad} - {self.cantidad_requisitar}'

templates/solicitud/cart.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<html>
<head>
{% block title %}Solicitudes{% endblock %}
</head>
<body>
{% block content %}
    <div class='row'>
        <div class='col-lg-12'>
            <div class='box-element'>
                <a class='btn btn-outline-dark' href="{% url 'solicitud-product-selection' %}"><i class="fa-solid fa-arrow-left"></i>Agregar más productos</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Productos: <strong>{{productosordenados}}</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class='btn btn-info' href="{% url 'solicitud-checkout' orden.id %}">Cargar artículos a solicitud</a>
                    </th>
                </tr>
            </table>
            </div>
            <br>
            <div class='box-element'>
                <div class='cart-row'>
                    <div style="flex:1"></div>
                    <div style="flex:1">Código</div>
                    <div style="flex:2">Artículo</div>
                    <div style="flex:1">Cantidad</div>
                </div>
                {% for producto in productos %}
                <div class='cart-row'>
                    <div style="flex:1"><img class='row-image' src="{{producto.producto.producto.imageURL}}"></div>
                    <div style="flex:1">{{producto.producto.producto.codigo}}</div>
                    <div style="flex:2">{{producto.producto.producto.nombre}}</div>
                    <div style="flex:1">
                        <p class='quantity'>{{producto.cantidad}}</p>
                        <div class='quantity'>
                            <img data-product={{producto.producto.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">

                            <img data-product={{producto.producto.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}">
                        </div>
                    </div>
                </div>
                <hr>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/solicitud/checkout.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Crear Solicitud{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>
<hr>
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <div id="Solicitud-info">
                <hr>
					<h2>Información de Solicitud:</h2>
					<hr>
					<form method="POST" id='OrderForm' data-subproyecto-url="{% url 'ajax_load_subproyectos' %}" novalidate>
                        {% csrf_token %}
                            <div class="row my-2">
                                <label for="form.proyecto" class="col-auto col-form-label my-1"><strong>Proyecto*</strong></label>
                                <div class="col-3">
                                    <div class="input-group">
                                    <!--    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-industry"></i></span>-->
                                    {{form.proyecto|add_class:"form-select"}}
                                    </div>
                                </div>
                            </div>
                            <div class="row my-2">
                                <label for="form.subproyecto" class="col-auto col-form-label my-1"><strong>Subproyecto*</strong></label>
                                <div class="col-3">
                                    <div class="input-group">
                                    <!--    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-industry"></i></span>-->
                                    {{form.subproyecto|add_class:"form-select"}}
                                    </div>
                                </div>
                            </div>
                            <div class="row my-2">
                                <label for="form.operacion" class="col-auto col-form-label my-1"><strong>Operación*</strong></label>
                                <div class="col-3">
                                    <div class="input-group">
                                    <!--    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-industry"></i></span>-->
                                    {{form.operacion|add_class:"form-select"}}
                                    </div>
                                </div>
                            </div>
                            <div class="row my-2">
                                <label for="form.activo" class="col-auto col-form-label my-1"><strong>Activo*</strong></label>
                                <div class="col-3">
                                    <div class="input-group">
                                    <!--    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-industry"></i></span>-->
                                    {{form.activo|add_class:"form-select"}}
                                    </div>
                                </div>
                            </div>
                            <div class="row my-2">
                            <label class="col-auto col-form-label" supervisores='{{supervisores}}'><strong>Supervisor*</strong></label>
                            <div class="col-3">
                                <div class="input-group">
                                <span class="input-group-text my-1" style="height:35px"><i class="fa-solid fa-user"></i></span>
                                <div class="selector">
                                    <select class="form-select form-select-sm my-1" style="height:35px" id="supervisores">
                                    <option id="default_sel">      </option>
                                    {% for supervisor in supervisores %}
                                    <option id="js" target="{{supervisor.id}}">
                                    {{supervisor.staff}}
                                    </option>
                                    {% endfor %}
                                    </select>
                                </div>
                                </div>
                            </div>
                            </div>

                            <div class="row my-2">
                            <label class="col-auto col-form-label" superintendentes='{{superintendentes}}'><strong>Superintendente*</strong></label>
                            <div class="col-3">
                                <div class="input-group">
                                <span class="input-group-text my-1" style="height:35px"><i class="fa-solid fa-user"></i></span>
                                <div class="selector">
                                    <select class="form-select form-select-sm my-1" style="height:35px" id="superintendentes">
                                    <option id="default_sel">      </option>
                                    {% for superintendente in superintendentes %}
                                    <option id="js" target="{{superintendente.id}}">
                                    {{superintendente.staff}}
                                    </option>
                                    {% endfor %}
                                    </select>
                                </div>
                                </div>
                            </div>
                            </div>
                            <div class="row my-2">
                                <label for="form.superintendente" class="col-auto col-form-label my-1 d-none"><strong>Superintendente*</strong></label>
                                <div class="col-3 d-none">
                                <!--<div class="input-group mb-3">-->
                                    <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                                    {{form.superintendente|add_class:"form-control"}}
                                </div>
                            </div>
                            <div class="row my-2">
                                <label for="form.supervisor" class="col-auto col-form-label my-1 d-none"><strong>Supervisor*</strong></label>
                                <div class="col-3 d-none">
                                <!--<div class="input-group mb-3">-->
                                    <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                                    {{form.supervisor|add_class:"form-control"}}
                                </div>
                            </div>
                        <input class="btn btn-outline-info btn-block my-2" name="agregar" type="submit" value="Agregar Solicitud">
                    </form>
            </div>
            <hr>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'solicitud-product-selection' %}"><i class="fa-solid fa-arrow-left">Agregar productos</i></a>
            <hr>
            <h3>Resumen de solicitud</h3>
            <hr>
            {% for producto in productos %}
            <div class='cart-row'>
                <table class="table table-ligth table-striped mx-1">
                <form method="POST">
                {% csrf_token %}
                <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Código</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col"></th>
                        </tr>
                </thead>
                <tbody>
                        <tr>
                            <th scope="col"><img class="row-image" src="{{producto.producto.producto.imageURL}}"></th>
                            <th scope="col">{{producto.producto.producto.codigo}}</th>
                            <th scope="col">{{producto.producto.producto.nombre}}</th>
                            <th scope="col">{{producto.cantidad}}</th>
                            <th scope="col">
                            <td>
                                <a class="btn btn-outline-info" id="btnActualizar" type="button" data-bs-toggle="modal" data-bs-target="#dialog" hx-target="#document" hx-get="{% url 'product-quantity-edit' producto.id %}">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <button type="button" class="btn btn-danger add-btn update-cart" value="Delete" data-product={{producto.producto.id}} data-action="remove" aria-label="Close"><i class="fa-solid fa-trash-can"></i></button>
                            </td>
                        </tr>
                </tbody>
                </form>
                </table>
            </div>
            <hr>
            {% endfor %}
            <h5>Artículos: {{orden.get_cart_quantity}}</h5>

        </div>
    </div>
    <div class="modal fade" id ="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered" id="document" role="document" hx-target="this">

        </div>
    </div>
</div>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $("#id_proyecto").change(function () {
      const url = $("#OrderForm").attr("data-subproyecto-url");  // get the url of the `load_subproyectos` view
      const proyectoId = $(this).val();  // get the selected proyecto ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'proyecto_id': proyectoId       // add the proyecto id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subproyectos` view function
          $("#id_subproyecto").html(data);  // replace the contents of the subproyectos input with the data that came from the server
        }
      });

    });

    ;(function(){
    const modal = new bootstrap.Modal(document.getElementById('dialog'))

    htmx.on('htmx:beforeSwap',(e)=>{
        if (e.detail.target.id === "document" && !e.detail.xhr.response)
        modal.hide()
    })
    })()

    var myModal = document.getElementById('dialog')

    myModal.addEventListener('hidden.bs.modal', function (event) {
    location.reload();
    })
    document.getElementById("supervisores").addEventListener("change", function(event){
    var select = document.getElementById("supervisores");
    var current_option = select.options[select.selectedIndex];
    var target = current_option.getAttribute('target')
    var other_select = document.getElementById('id_supervisor')
    other_select.value = target
    });
    document.getElementById("superintendentes").addEventListener("change", function(event){
    var select = document.getElementById("superintendentes");
    var current_option = select.options[select.selectedIndex];
    var target = current_option.getAttribute('target')
    var other_select = document.getElementById('id_superintendente')
    other_select.value = target
    });
</script>
{% endblock %}
</body>
</html>

templates/solicitud/checkout_editar.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<html>
<head>
{% block title %}Crear Solicitud{% endblock %}
</head>
<body>
{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <div id="Solicitud-info">
                <hr>
					<h2>Información de Solicitud:</h2>
					<hr>
					<form method="POST" id='OrderForm' data-subproyecto-url="{% url 'ajax_load_subproyectos' %}" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-outline-info btn-block" type="submit" value="Agregar Solicitud">
                    </form>
            </div>
            <hr>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'solicitud-cart' %}">&#x2190;De vuelta al carro</a>
            <hr>
            <h3>Resumen de solicitud</h3>
            <hr>
            {% for producto in productos %}
            <div class='cart-row'>
                <div style="flex:2"><img class="row-image" src="{{producto.producto.producto.imageURL}}"></div>
                <div style="flex:1">{{producto.producto.producto.codigo}}</div>
                <div style="flex:2">{{producto.producto.producto.nombre}}</div>
                <div style="flex:1">
                <p class='quantity'>{{producto.cantidad}}</p>
                </div>
            </div>
            {% endfor %}
            <hr>
            <h5>Artículos: {{orden.get_cart_quantity}}</h5>

        </div>
    </div>
</div>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $("#id_proyecto").change(function () {
      const url = $("#OrderForm").attr("data-subproyecto-url");  // get the url of the `load_subproyectos` view
      const proyectoId = $(this).val();  // get the selected proyecto ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'proyecto_id': proyectoId       // add the proyecto id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subproyectos` view function
          $("#id_subproyecto").html(data);  // replace the contents of the subproyectos input with the data that came from the server
        }
      });

    });
  </script>
{% endblock %}
</body>
</html>

templates/solicitud/checkout_resurtimiento.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Crear Solicitud{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>
<hr>
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <div id="Solicitud-info">
                <hr>
					<h2>Información de Solicitud:</h2>
					<hr>
					<form method="POST" id='OrderForm' data-subproyecto-url="{% url 'ajax_load_subproyectos' %}" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-outline-info btn-block my-2" name="agregar" type="submit" value="Agregar Solicitud">
                    </form>
            </div>
            <hr>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'product_selection_resurtimiento' %}"><i class="fa-solid fa-arrow-left">Agregar productos</i></a>
            <hr>
            <h3>Resumen de Solicitud</h3>
            <hr>
            {% for producto in productos %}
            <div class='cart-row'>
                <table class="table table-ligth table-striped mx-1">
                <form method="POST">
                {% csrf_token %}
                <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Código</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col"></th>
                        </tr>
                </thead>
                <tbody>
                        <tr>
                            <th scope="col"><img class="row-image" src="{{producto.producto.producto.imageURL}}"></th>
                            <th scope="col">{{producto.producto.producto.codigo}}</th>
                            <th scope="col">{{producto.producto.producto.nombre}}</th>
                            <th scope="col">{{producto.cantidad}}</th>
                            <th scope="col">
                            <td>
                                <a class="btn btn-outline-info" id="btnActualizar" type="button" data-bs-toggle="modal" data-bs-target="#dialog" hx-target="#document" hx-get="{% url 'product-quantity-edit' producto.id %}">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <button type="button" class="btn btn-danger add-remove" value="Delete" data-product={{producto.producto.id}} data-action="remove" aria-label="Close"><i class="fa-solid fa-trash-can"></i></button>
                            </td>
                        </tr>
                </tbody>
                </form>
                </table>
            </div>
            <hr>
            {% endfor %}
            <h5>Artículos: {{orden.get_cart_quantity}}</h5>

        </div>
    </div>
    <div class="modal fade" id ="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered" id="document" role="document" hx-target="this">

        </div>
    </div>
</div>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $("#id_proyecto").change(function () {
      const url = $("#OrderForm").attr("data-subproyecto-url");  // get the url of the `load_subproyectos` view
      const proyectoId = $(this).val();  // get the selected proyecto ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'proyecto_id': proyectoId       // add the proyecto id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subproyectos` view function
          $("#id_subproyecto").html(data);  // replace the contents of the subproyectos input with the data that came from the server
        }
      });

    });

    ;(function(){
    const modal = new bootstrap.Modal(document.getElementById('dialog'))

    htmx.on('htmx:beforeSwap',(e)=>{
        if (e.detail.target.id === "document" && !e.detail.xhr.response)
        modal.hide()
    })
    })()

    var myModal = document.getElementById('dialog')

    myModal.addEventListener('hidden.bs.modal', function (event) {
    location.reload();
    })
</script>
{% endblock %}
</body>
</html>