compras/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('compras/requisiciones_autorizadas', views.requisiciones_autorizadas, name='requisicion-autorizada'),
    path('compras/oc/<int:pk>/', views.oc_modal, name='oc'),
    path('update_oc/', views.update_oc, name='update-oc'),
    path('compras/matriz_compras/', views.matriz_oc, name='matriz-compras'),
    path('compras/upload_facturas/<int:pk>/', views.upload_facturas, name='upload-facturas'),
    path('compras/upload_xml/<int:pk>/', views.upload_xml, name='upload-xml'),
    path('compras/autorizacion_oc1/',views.autorizacion_oc1, name='autorizacion-oc1'),
    path('compras/autorizacion_oc2/',views.autorizacion_oc2, name='autorizacion-oc2'),
    path('compras/cancelar_oc1/<int:pk>/',views.cancelar_oc1, name='cancelar-oc1'),
    path('compras/regresar_oc/<int:pk>/',views.back_oc, name='back-oc'),
    path('compras/cancelar_oc2/<int:pk>/',views.cancelar_oc2, name='cancelar-oc2'),
    path('compras/autorizar_oc1/<int:pk>/', views.autorizar_oc1, name='autorizar-oc1'),
    path('compras/autorizar_oc2/<int:pk>/', views.autorizar_oc2, name='autorizar-oc2'),
    path('salida_material/oc_pdf/<int:pk>/', views.render_oc_pdf, name='oc-pdf'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

dashboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('dashboard/', views.index, name= 'dashboard-index'),
    path('staff/', views.staff, name='dashboard-staff'),
    path('product/', views.product, name='dashboard-product'),
    path('product/upload_batch_products', views.upload_batch_products, name='upload_batch_products'),
    path('order/', views.order, name='dashboard-order'),
    path('product/delete/<int:pk>/', views.product_delete, name='dashboard-product-delete'),
    path('product/update/<int:pk>/', views.product_update, name='dashboard-product-update'),
    path('product/add/', views.add_product, name='add-product'),
    path('ajax/load-subfamilias/', views.load_subfamilias, name='ajax_load_subfamilias'),  # <-- rutina en Ajax
    path('dashboard/staff_detail/<int:pk>/', views.staff_detail, name='dashboard-staff-detail'),
]

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
# De django.contrib.auth.models estamos importando el modelo de usuarios de la administration
from user.models import Distrito, Profile
from solicitudes.models import Proyecto, Subproyecto, Sector, Operacion, Activo
from djmoney.models.fields import MoneyField
from simple_history.models import HistoricalRecords
#from django.db.models.functions import TruncDate

# Create your models here.

class Familia(models.Model):
    nombre = models.CharField(max_length=20, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Unidad(models.Model):
    nombre = models.CharField(max_length=10, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Subfamilia(models.Model):
    nombre = models.CharField(max_length=15, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Product(models.Model):
    codigo = models.CharField(max_length=5, null=True, unique=True)
    nombre = models.CharField(max_length=100, null=True, unique=True)
    unidad = models.ForeignKey(Unidad, on_delete = models.CASCADE, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)
    subfamilia = models.ForeignKey(Subfamilia, on_delete =models.CASCADE, null=True)
    especialista = models.BooleanField(default=False)
    iva = models.BooleanField(default=True)
    activo = models.BooleanField(default=False)
    servicio = models.BooleanField(default=False)
    baja_item = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, upload_to='product_images')
    completado = models.BooleanField(default = False)

    #Estas opciones de guardado de creación y actualización las voy a utilizar en todos mis modelos
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.codigo}-{self.nombre}'


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Products_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash')
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)


    def __str__(self):
        return f'File id:{self.id}'



class Marca(models.Model):
    nombre = models.CharField(max_length=20, null=True, unique=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Inventario_Batch(models.Model):
    file_name = models.FileField(upload_to='inventario_batch')
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f'File id:{self.id}'

class Inventario(models.Model):
    producto = models.ForeignKey(Product, on_delete =models.CASCADE, null=True)
    distrito = models.ForeignKey(Distrito, on_delete = models.CASCADE, null=True)
    marca = models.ManyToManyField(Marca)
    cantidad = models.PositiveIntegerField(default=0)
    cantidad_apartada = models.PositiveIntegerField(default=0)
    cantidad_entradas = models.PositiveIntegerField(default=0)
    price = MoneyField(max_digits=14, decimal_places=2,default_currency= 'MXN',default=0)
    minimo = models.PositiveIntegerField(default =0)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    comentario = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        unique_together = ('producto', 'distrito',)

    def __str__(self):
        return f'{self.producto}'

class Tipo_Orden(models.Model):
    tipo = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f'{self.id}:{self.tipo}'

class Order(models.Model):
    folio = models.CharField(max_length=6, null=True, unique=True)
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Crea')
    proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)
    operacion = models.ForeignKey(Operacion, on_delete = models.CASCADE, null=True)
    #sector = models.ForeignKey(Sector, on_delete = models.CASCADE, null=True)
    superintendente = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='intendente')
    supervisor = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='supervisor')
    activo = models.ForeignKey(Activo, on_delete = models.CASCADE, null=True)
    requisitar = models.BooleanField(null=True, default=False)
    complete = models.BooleanField(null=True)
    tipo = models.ForeignKey(Tipo_Orden, on_delete=models.CASCADE, null=True)
    #sol_autorizada_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, blank=True, related_name='Autoriza')
    autorizar = models.BooleanField(null=True, default=None)
    created_at = models.DateField(null=True)
    created_at_time = models.TimeField(null=True)
    approved_at = models.DateField(null=True)
    approved_at_time = models.TimeField(null=True)

    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.id} -{self.folio} ordered by {self.staff}'


    @property
    def get_cart_total(self):
        productos = self.articulosordenados_set.all()
        total = sum([producto.get_total for producto in productos])
        return total

    @property
    def get_cart_quantity(self):
        productos = self.articulosordenados_set.all()
        total = sum([producto.cantidad for producto in productos])
        return total

    @property
    def get_folio(self):
        return str(self.pk).zfill(6)


class ArticulosOrdenados(models.Model):
    producto = models.ForeignKey(Inventario, on_delete = models.CASCADE, null=True)
    orden = models.ForeignKey(Order, on_delete = models.CASCADE, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.orden} - {self.producto}'

    @property
    def get_total(self):
        total = self.producto.price * self.cantidad
        return total

class ArticulosparaSurtir(models.Model):
    articulos = models.ForeignKey(ArticulosOrdenados, on_delete = models.CASCADE, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank= True)
    precio = MoneyField(max_digits=14, decimal_places=2, default_currency= 'MXN',default=0)
    surtir = models.BooleanField(default=False)
    cantidad_requisitar = models.IntegerField(default=0, null=True, blank=True)
    requisitar = models.BooleanField(null=True, default=False)
    salida = models.BooleanField(null=True, default=False)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    seleccionado = models.BooleanField(null=True, default=False)
    created_at = models.DateField(auto_now_add=True)
    created_at_time = models.TimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)


    def __str__(self):
        return f'{self.articulos} - {self.cantidad} - {self.cantidad_requisitar}'

dashboard/forms.py
from django import forms
from .models import Product, Subfamilia, Products_Batch, Inventario_Batch


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['familia','subfamilia','unidad','especialista','iva','activo','servicio','baja_item','image',]

#Sobreescribiendo el método __init__ y configurando el queryset para que esté vacío
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subfamilia'].queryset = Subfamilia.objects.none()

        if 'familia' in self.data:
            try:
                familia_id = int(self.data.get('familia'))
                self.fields['subfamilia'].queryset = Subfamilia.objects.filter(familia_id=familia_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['subfamilia'].queryset = self.instance.familia.subfamilia_set.order_by('nombre')

class Products_BatchForm(forms.ModelForm):
    class Meta:
        model = Products_Batch
        fields= ['file_name']

class Inventario_BatchForm(forms.ModelForm):
    class Meta:
        model = Inventario_Batch
        fields= ['file_name']

class AddProduct_Form(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['codigo','nombre','unidad','familia','subfamilia','especialista','iva','activo','servicio','image',]

#Sobreescribiendo el método __init__ y configurando el queryset para que esté vacío
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subfamilia'].queryset = Subfamilia.objects.none()

        if 'familia' in self.data:
            try:
                familia_id = int(self.data.get('familia'))
                self.fields['subfamilia'].queryset = Subfamilia.objects.filter(familia_id=familia_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['subfamilia'].queryset = self.instance.familia.subfamilia_set.order_by('nombre')

templates/dashboard/add_product.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Agregar Producto/Servicio{% endblock %}
</head>
<body>
{% block content %}
<hr>
<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3">
                <h3>Agregar Producto/Servicio</h3>
                <hr>
                <form method="POST" id='ProductForm' enctype='multipart/form-data' data-subfamilias-url="{% url 'ajax_load_subfamilias' %}" novalidate>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <a class="btn btn-outline-secondary" href="{% url 'dashboard-product' %}">Cancelar</a>
                    <input class="btn btn-outline-info" type='submit' value="Actualizar">
                </form>
            </div>
        </div>

    </div>
</div>
</body>
</html>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $("#id_familia").change(function() {
      var url = $("#ProductForm").attr("data-subfamilias-url");  // get the url of the `load_subfamilias` view
      var familiaId = $(this).val();  // get the selected familia ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'familia_id': familiaId       // add the familia id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subfamilias` view function
          $("#id_subfamilia").html(data);  // replace the contents of the subfamilia input with the data that came from the server
        }
      });

    });
  </script>
{% endblock %}

templates/dashboard/inventario_delete.html
<h6>No tienes permisos para borrar artículos</h6>

templates/dashboard/product.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load tt_extras %}
<html>
<head>
{% block title %}Product Page{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>

<!-- Esta es la zona donde se crean los mensajes perrones con sweet alert -->
<div class="row my-4">
    <div class="col-md-4">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                <script>
                Swal.fire({
                    "title":"Error",
                    "text":"{{message}}",
                    "icon":"error",
                })
                </script>
                {% else %}
                <script>
                Swal.fire({
                    "title":"Excelente",
                    "text":"{{message}}",
                    "icon":"success",
                })
                </script>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>
<div class = "row mt-2 bg-white">
        <div class="col-12">
            <div class="card card-body">
                <h5>Filtro de Solicitudes Autorizadas</h5>
                <hr>
                {% csrf_token %}
                <form method="GET">
                <div class="row g-12">
                    <label for="myfilter.form.codigo" class="col-sm-auto col-form-label text-right my-2"><strong>Código:</strong></label>
                    <div class="col-auto my-2">
                        {{myfilter.form.codigo|add_class:'form-control'}}
                    </div>
                    <label for="myfilter.form.codigo" class="col-sm-auto col-form-label text-right my-2"><strong>Producto:</strong></label>
                    <div class="col-auto my-2">
                        {{myfilter.form.nombre|add_class:'form-control'}}
                    </div>
                    <label for="myfilter.form.familia" class="col-sm-auto col-form-label text-right my-2"><strong>Familia:</strong></label>
                    <div class="col-auto my-2">
                        {{myfilter.form.familia|add_class:'form-control'}}
                    </div>
                    <label for="myfilter.form.subfamilia" class="col-sm-auto col-form-label text-right my-2"><strong>Subfamilia:</strong></label>
                    <div class="col-auto my-2">
                        {{myfilter.form.subfamilia|add_class:'form-control'}}
                    </div>
                    <div class="col-2">
                        <button class="btn btn-outline-success btn-block my-2" type="submit" value="Buscar"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </div>
                </div>
                <hr>
                </form>
                    <ul class="nav nav-pills">
                        <li class="nav-item mx-2">
                            <a type="button" class="btn btn-outline-light" style="background-color:#9a9b9d" data-bs-toggle="modal" data-bs-target='#dialog' hx-target="#document" hx-get="{% url 'upload_batch_products' %}">
                                <i class="fa-solid fa-file-arrow-up"> CARGA MASIVA</i>
                            </a>
                            <a class="btn btn-outline-info" id="btnActualizar" type="button" href="{% url 'add-product' %}">
                                <i class="fa-solid fa-plus"> AGREGAR PRODUCTO</i>
                            </a>
                        </li>
                    </ul>
            </div>
        </div>
</div>

    <div class="col-md-8 my-2">
        <table class="table bg-white">
            <thead class="text-black" style="background-color: #F5F5F5;">
                <tr>
                    <th scope="col">Código</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Familia</th>
                    <th scope="col">Subfamilia</th>
                    <th scope="col">Unidad</th>
                    <th scope="col">IVA</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items_list %}
                <tr>
                    <th scope="row">{{item.codigo}}</th>
                    <td>{{item.nombre}}</td>
                    <td>{{item.familia}}</td>
                    <td>{{item.subfamilia}}</td>
                    <td>{{item.unidad}}</td>
                    <td>{{item.iva}}</td>
                    <td>
                        <a class="btn btn-outline-info" id="btnActualizar" type="button" href="{% url 'dashboard-product-update' item.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
                    </td>
                    <!--
                    <a class="btn btn-outline-danger" href="{% url 'dashboard-product-delete' item.id %}">Eliminar</a></td> -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if items_list.has_previous %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="?page=1"><i class="fa-solid fa-angles-left"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="?page={{items_list.previous_page_number}}"><i class="fa-solid fa-angle-left"></i></a></li>
            {% endif %}
            <!--<li class="page-item disabled"><a href="#" class="page-link">Page {{items_list.number}} of {{ items_list.paginator.num_pages}}</a></li>-->

            {% for item in items_list.paginator.page_range %}
                {% if items_list.number == item %}
                    <li class="page-item active"><a href="#" class="page-link bg-dark">{{item}}</a></li>
                {% elif item > items_list.number|add:'-2' and item < items_list.number|add:'2' %}
                    <li class="page-item "><a class="page-link" style="color:#3E92CC" href="?page={{item}}" class="page-link">{{item}}</a></li>
                {% endif %}
            {% endfor %}

            {% if items_list.paginator.num_pages > items_list.number|add:'2' %}
            <li><a class="page-link" style="color:#3E92CC" href="?page={{items_list.number|add:'2'}}">&hellip;</a></li>
            <li><a style="color:#3E92CC" href="?page={{ item }}">{{item}}</a></li>
            <li><a class="page-link" style="color:#3E92CC" href="?page={{ items_list.paginator.num_pages}}">{{items_list.paginator.num_pages}}</a></li>
            {% endif %}

            {% if items_list.has_next %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="?page={{items_list.next_page_number}}"><i class="fa-solid fa-chevron-right"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="?page={{items_list.paginator.num_pages}}"><i class="fa-solid fa-angles-right"></i></a></a></li>
            {% endif %}
        </ul>
    </nav>
<!--Este es el modal-->
        <div class="modal fade" id ="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-centered" id="document" role="document" hx-target="this">

            </div>
        </div>
</body>
</html>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $("#id_familia").change(function () {
      const url = $("#ProductForm").attr("data-subfamilias-url");  // get the url of the `load_subfamilias` view
      const familiaId = $(this).val();  // get the selected familia ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'familia_id': familiaId       // add the familia id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subfamilias` view function
          $("#id_subfamilia").html(data);  // replace the contents of the subfamilia input with the data that came from the server
        }
      });
    });

    ;(function(){
        const modal = new bootstrap.Modal(document.getElementById('dialog'))

        htmx.on('htmx:beforeSwap',(e)=>{
            if (e.detail.target.id === "document" && !e.detail.xhr.response)
                modal.hide()
        })
    })()

    var myModal = document.getElementById('dialog')

    myModal.addEventListener('hidden.bs.modal', function (event) {
        location.reload();
    })
  </script>
{% endblock %}

<!--style="background-color: #D0D8DC; color:black; font-weight: bold;" -->
<!--style="background-color: #515151; color:white;"-->
<!--style="background-color: #711F1B; color:white;"-->

templates/dashboard/product_update_modal.html
{% extends 'partials/base_w_nav.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<html>
<head>
{% block title %} Actualización de Producto {% endblock %}
</head>
<body>
{% block content %}
<div class="modal-dialog-lg" role="document">
    <form  hx-post="{{request.path}}" class="modal-content" id='ProductForm' enctype='multipart/form-data' data-subfamilias-url="{% url 'ajax_load_subfamilias' %}" novalidate>
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Actualizar Productos</h5>
            <button class="btn-close cerrar" type="button" id="cerrar1" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="color:white">
                {% csrf_token %}
                <label for="form.codigo" class="col-auto col-form-label"><strong>Código: {{item.codigo}}</strong></label>
                <br>
                <label for="form.nombre" class="col-auto col-form-label"><strong>Producto: {{item.nombre}}</strong></label>
                <br>
                <!--<label for="form.unidad" class="col-auto col-form-label my-1"><strong>Marca:</strong></label>
                    <div class="col-4">
                        {{ form.unidad|add_class:"form-control"}}
                    </div>
                <label for="form.familia" class="col-auto col-form-label my-1"><strong>Familia:</strong></label>
                    <div class="col-4">
                        {{ form.familia|add_class:"form-control"}}
                    </div>
                <label for="form.subfamilia" class="col-auto col-form-label my-1"><strong>Subfamilia:</strong></label>
                    <div class="col-4">
                        {{ form.subfamilia|add_class:"form-control"}}
                    </div>
                <label for="form.especialista" class="col-auto col-form-label my-1"><strong>Especialista:</strong></label>
                    <div class="col-4">
                        {{ form.especialista|add_class:"form-check-input"}}
                    </div>
                <label for="form.iva" class="col-auto col-form-label my-1"><strong>Iva:</strong></label>
                    <div class="col-4">
                        {{ form.iva|add_class:"form-check-input"}}
                    </div>
                <label for="form.activo" class="col-auto col-form-label my-1"><strong>Activo:</strong></label>
                    <div class="col-4">
                        {{ form.activo|add_class:"form-check-input"}}
                    </div>
                <label for="form.servicio" class="col-auto col-form-label my-1"><strong>Servicio:</strong></label>
                    <div class="col-4">
                        {{ form.servicio|add_class:"form-check-input"}}
                    </div>
                <label for="form.baja_item" class="col-auto col-form-label my-1"><strong>Baja Item:</strong></label>
                    <div class="col-4">
                        {{ form.baja_item|add_class:"form-check-input"}}
                    </div>
                <div class="col-10">
                        {{form.image|add_class:"form-control"}}
                </div>-->
                {{form|crispy}}
        </div>
        <div class="modal-footer">
                <button class="btn btn-success col-auto" id="crear" type="submit" >Actualizar</button>
                <a type="button" class="btn btn-secondary" id="cerrar" data-bs-dismiss="modal">Cerrar</a>
        </div>
    </div>
    </form>
</div>

<!--Este es el modal-->
<!--Este es el modal-->
<div class="modal fade" id ="dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" id="document" role="document" hx-target="this">

    </div>
</div>
<!--AJAX CALL-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
$("#id_familia").change(function () {
      const url = $("#ProductForm").attr("data-subfamilias-url");  // get the url of the `load_subfamilias` view
      const familiaId = $(this).val();  // get the selected familia ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'familia_id': familiaId       // add the familia id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subfamilias` view function
          $("#id_subfamilia").html(data);  // replace the contents of the subfamilia input with the data that came from the server
        }
      });
    });
</script>
{% endblock %}
</body>
</html>